MOUSEKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes
NKRO_ENABLE = yes
AUDIO_ENABLE = no
BOOTMAGIC_ENABLE = no
EXTRAKEY_ENABLE  = no
CONSOLE_ENABLE   = no
MIDI_ENABLE      = no
BLUETOOTH_ENABLE = no
RGBLIGHT_ENABLE  = no
SLEEP_LED_ENABLE = no

ifndef QUANTUM_DIR
	include ../../../../Makefile
endif
